CREATE DATABASE EASYBOXDB
GO
USE EASYBOXDB
GO

-- Tabla de roles
CREATE TABLE ROLES(
	id_rol TINYINT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL
)
GO

-- Tabla de usuarios
CREATE TABLE USUARIOS (
	id_usuario INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(220) NOT NULL,
	rol TINYINT NOT NULL FOREIGN KEY REFERENCES ROLES(id_rol),
	img_perfil VARCHAR(100) NULL,
	eliminado BIT NOT NULL DEFAULT 0,
	fecha_creacion DATETIME DEFAULT GETDATE()
)
GO

-- Tabla de categorías
CREATE TABLE CATEGORIAS (
	id_categoria TINYINT IDENTITY (1,1) PRIMARY KEY,
	categoria VARCHAR(50) NOT NULL UNIQUE
)
GO

-- Tabla de monedas
CREATE TABLE MONEDAS (
	id_moneda TINYINT IDENTITY PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	signo VARCHAR(5) NOT NULL,
	codigo VARCHAR(3) NOT NULL UNIQUE
)
GO

-- Tabla de cajas
CREATE TABLE CAJAS (
	id_caja INT IDENTITY (1000, 1) PRIMARY KEY,
	moneda TINYINT NOT NULL FOREIGN KEY REFERENCES MONEDAS(id_moneda),
	saldo DECIMAL (18,2) DEFAULT 0.00,
	eliminado BIT NOT NULL DEFAULT 0
)
GO

-- Tabla de transacciones
CREATE TABLE TRANSACCIONES (
	id_transaccion INT IDENTITY (1,1) PRIMARY KEY,
	creador INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id_usuario),
	descripcion VARCHAR(180),
	categoria TINYINT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(id_categoria),
	monto DECIMAL (18,2) NOT NULL,
	caja INT NOT NULL FOREIGN KEY REFERENCES CAJAS(id_caja),
	tipo_movimiento CHAR(7) NOT NULL,
	fecha_movimiento DATETIME DEFAULT GETDATE() NOT NULL,
	eliminado BIT NOT NULL DEFAULT 0,
	CONSTRAINT CHK_TIPOMOVIMIENTO CHECK (tipo_movimiento IN ('RETIRO', 'INGRESO'))
)
GO

-- Tabla de historial de transacciones
CREATE TABLE HISTORIAL_TRANSACCIONES (
	id_historial INT IDENTITY(1,1) PRIMARY KEY,
	id_transaccion INT NOT NULL FOREIGN KEY REFERENCES TRANSACCIONES(id_transaccion),
	descripcion VARCHAR(180),
	categoria TINYINT NOT NULL,
	monto DECIMAL (18,2) NOT NULL,
	tipo_movimiento CHAR(7) NOT NULL,
	fecha_movimiento DATETIME NOT NULL,
	fecha_modificacion DATETIME DEFAULT GETDATE() NOT NULL,
	accion VARCHAR(20) NOT NULL CHECK (accion IN ('CREACION', 'MODIFICACION', 'ELIMINACION'))
)
GO

