CREATE DATABASE EASYBOXDB
GO
USE EASYBOXDB
GO
CREATE TABLE ROLES(
	id_rol TINYINT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(20) NOT NULL,
)
GO
CREATE TABLE CREDENCIALES (
	id_credencial INT IDENTITY (1,1) PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	contraseña VARCHAR(220) NOT NULL,
	rol TINYINT NOT NULL FOREIGN KEY REFERENCES ROLES(id_rol),
)
GO
CREATE TABLE USUARIOS (
	id_usuario INT IDENTITY (1,1) PRIMARY KEY,
	credencial INT NOT NULL FOREIGN KEY REFERENCES CREDENCIALES(id_credencial),
	img_perfil VARCHAR(100) NULL,
	fecha_creacion DATETIME DEFAULT GETDATE(),
)
GO
CREATE TABLE CATEGORIAS (
	id_categoria TINYINT IDENTITY (1,1) PRIMARY KEY,
	categoria VARCHAR(50) NOT NULL UNIQUE,
)
GO
CREATE TABLE MONEDAS (
	id_moneda TINYINT IDENTITY PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	signo VARCHAR(5) NOT NULL,
	codigo VARCHAR(3) NOT NULL UNIQUE,
)
GO
CREATE TABLE CAJAS (
	id_caja INT IDENTITY (1000, 1) PRIMARY KEY,
	moneda TINYINT NOT NULL FOREIGN KEY REFERENCES MONEDAS(id_moneda),
	saldo DECIMAL (18,2) DEFAULT 0.00,
)
GO
CREATE TABLE TRANSACCIONES (
	id_transaccion INT IDENTITY (1,1) PRIMARY KEY,
	creador INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(id_usuario),
	descripcion VARCHAR(180),
	categoria TINYINT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(id_categoria),
	monto DECIMAL (18,2) NOT NULL,
	moneda TINYINT NOT NULL FOREIGN KEY REFERENCES MONEDAS(id_moneda),
	tipo_movimiento VARCHAR(50),
	caja INT NOT NULL FOREIGN KEY REFERENCES CAJAS(id_caja),
	fecha_movimiento DATETIME DEFAULT GETDATE() NOT NULL,
	CONSTRAINT CHK_TIPOMOVIMIENTO CHECK (tipo_movimiento IN ('RETIRO', 'INGRESO'))
)

